### ISSUE TITLE
LROAuth2Client.m:158 warning: 'ASIHTTPRequest' may not respond to '+uncompressZippedData:'   

### ISSUE THREAD

**Issue by pooch** [lukeredpath/LROAuth2Client#4]
Hello lukeredpath,

I'm getting the title warning when building my app that's trying to use your LROAuth2Client.  (It's the only warning when I build my project with your source code and ASIHTTPRequest source code in vendor folders.)

I can't tell which version of ASIHTTPRequest you require.  Can you tell me?

Thanks,

Phil

**Comment by precipice** [comment]
The current LROAuth2Client has an older submodule definition for ASIHTTPRequest, so it depends on a method that ASI has since removed.

If you are using a more recent ASIHTTPRequest, these two change fix the call: precipice/LROAuth2Client@c9f3f1d89addefc37e5f47409385680846c7c144 and precipice/LROAuth2Client@15149dcccac16374fc46a255523f2b8a93fd8373

**Comment by pooch** [comment]
Those fixes took care of it.  Thanks very much!
